### ISSUE TITLE
ModuleNotFoundError: No module named 'audio_diffusion'

### ISSUE THREAD

**Issue by frogs-sb** [diontimmer/AIAudioUpsampling#1]
After installing torch, torch audio, and the requirements.txt, trying to use cli.py gives the following error:

```
Traceback (most recent call last):
  File "T:\Software\AIAudioUpsampling-main\cli.py", line 3, in <module>
    from AIAU_models import *
  File "T:\Software\AIAudioUpsampling-main\AIAU_models.py", line 1, in <module>
    from audio_diffusion.models import DiffusionAttnUnet1D
ModuleNotFoundError: No module named 'audio_diffusion'
```

I double checked that audio-diffusion-pytorch really is installed, along with everything else, and it seems to be. I'm on Win10, Python 3.10.6.

**Comment by Susukerow45** [comment]
Download code from this page: https://github.com/Harmonai-org/sample-generator and install manualy from folder using pip3. 
Prefer to have virtual env to build.
